Repository 100-hours-a-week/4-bull4zo-fe, pull requests merged in 2025-07, with the labels that each got.

#224 feat: 알림 sse 개발
  package.json
  pnpm-lock.yaml
  src/api/services/notification/model.ts
  src/api/services/notification/queries.ts
  src/app/AppLayout.tsx
  src/components/header/header.tsx
  src/components/item/notificationItem.tsx
  src/components/slider/slider.tsx
  src/hooks/useSSE.ts
  src/lib/messageMap.ts
  src/mocks/handlers/notificationHandlers.ts
  src/stores/notificationStore.ts
Labels: ✨ Feature, 🌐 FE

#240 feat: 드롭다운 피드백 반영
  src/components/dropdown/groupDropDown.tsx
  src/components/ui/dropdown-menu.tsx
Labels: 🐛 BugFix, ✨ Feature, 🌐 FE

#253 cicd: prod 서버 aws 환경 CI/CD 파이프라인 구축
  .github/workflows/aws-v3-deployment.yml
  .husky/pre-commit
Labels: CI/CD
