Repository 100-hours-a-week/4-bull4zo-fe, pull requests merged in 2025-05, with the labels that each got.

#39 [Feat] 카드 인터렉션 개선
  package.json
  pnpm-lock.yaml
  src/components/card/voteCard.tsx
  src/components/card/voteEndCard.tsx
  src/components/card/voteNoMoreCard.tsx
  src/features/home/components/swipCard.tsx
  src/features/home/components/voteSwiper_framer.tsx
  src/features/home/components/voteSwiper_tinder.tsx
  src/features/home/pages/homePage.tsx
  src/features/home/stores/batchVoteStore.ts
  src/features/login/pages/authCallback.tsx
  src/mocks/handlers/loginHandlers.ts
Labels: 개발, FE

#40 [Feat] Home 페이지 개발
  package.json
  pnpm-lock.yaml
  src/api/services/vote/model.ts
  src/api/services/vote/quries.ts
  src/api/services/vote/service.ts
  src/components/card/voteCard.tsx
  src/components/card/voteEndCard.tsx
  src/components/card/voteNoMoreCard.tsx
  src/components/loading/loadingCard.tsx
  src/components/modal/loginRequiredModal.tsx
  src/components/modal/modal.tsx
  src/components/modal/noVoteAvailableModal.tsx
  src/components/navigation/navigation.tsx
  src/features/home/components/swipCard.tsx
  src/features/home/components/voteSwiper_framer.tsx
  src/features/home/components/voteSwiper_tinder.tsx
  src/features/home/pages/homePage.tsx
  src/features/home/stores/batchVoteStore.ts
  src/features/login/pages/authCallback.tsx
  src/lib/formatTime.ts
  src/mocks/handlers/loginHandlers.ts
  src/mocks/handlers/voteCardHandlers.ts
  src/stores/modalStore.ts
  tsconfig.app.json
  tsconfig.node.json
Labels: 개발, FE

#43 [Feat] input 공통 컴포넌트 제작
  src/api/services/user/model.ts
  src/api/services/user/quries.ts
  src/api/services/user/service.ts
  src/api/services/vote/model.ts
  src/api/services/vote/quries.ts
  src/api/services/vote/service.ts
  src/components/navigation/navigation.tsx
  src/components/ui/button.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/textarea.tsx
  src/features/home/components/swipCard.tsx
  src/features/home/pages/homePage.tsx
  src/features/make/components/makeVoteForm.tsx
  src/features/make/lib/makeVoteSchema.ts
  src/lib/globalTime2LocalTime.ts
  src/mocks/handlers/voteCardHandlers.ts
  src/stores/userStore.ts
Labels: 개발, FE

#46 [Feat] 투표등록 페이지 개발
  src/app/router.tsx
  src/components/card/voteCardPreview.tsx
  src/features/make/components/voteCardPreviewModal.tsx
  src/features/make/pages/makePage.tsx
Labels: 개발, FE

#48 [Feat] navgtaion 오류 해결
  src/app/AppLayout.tsx
  src/app/router.tsx
  src/components/navigation/navigation.tsx
  src/features/login/pages/authCallback.tsx
  src/features/login/pages/loginPage.tsx
  src/stores/navigationStore.ts
Labels: 개발, FE

#50 [Feat] 투표 결과 페이지 개발
  src/api/services/vote/model.ts
  src/api/services/vote/quries.ts
  src/api/services/vote/service.ts
  src/app/router.tsx
  src/components/item/voteItem.tsx
  src/components/list/voteList.tsx
  src/features/research/components/researchList.tsx
  src/features/research/components/topList.tsx
  src/features/research/pages/researchPage.tsx
  src/mocks/handlers/voteCardHandlers.ts
  src/styles/utilities/shadow.css
Labels: 개발, FE

#51 [CICD] 빅뱅배포용 CICD 파이프라인 생성
  .github/workflows/cicd-bigbang-dev.yml
Labels: CI/CD

#54 [BuxFix] 투표등록페이지 API오류 해결
  package.json
  pnpm-lock.yaml
  src/api/services/vote/model.ts
  src/components/card/voteCardPreview.tsx
  src/components/ui/checkbox.tsx
  src/features/make/components/makeVoteForm.tsx
  src/features/make/components/voteCardPreviewModal.tsx
  src/features/make/lib/makeVoteSchema.ts
Labels: 🐛 BugFix, 🌐 FE

#55 [Feat] 투표상세 페이지 개발
  src/api/services/vote/model.ts
  src/api/services/vote/quries.ts
  src/api/services/vote/service.ts
  src/app/router.tsx
  src/components/item/voteItem.tsx
  src/features/research/pages/researchDetail.Page.tsx
  src/mocks/handlers/index.ts
  src/mocks/handlers/researchHandlers.ts
  src/styles/utilities/color.css
Labels: ✨ Feature, 🌐 FE

#57 [bugfix] 메인 라벨 수정 및 모달 오류 수정
  src/assets/dislike.svg
  src/assets/like.svg
  src/assets/pass.svg
  src/components/navigation/navigation.tsx
  src/features/home/components/voteSwiper_framer.tsx
  src/features/home/pages/homePage.tsx
  src/mocks/handlers/voteCardHandlers.ts
Labels: 🐛 BugFix, 🌐 FE, 💎 Style

#59 [Feat] 홈의 무한 스크롤 및 블링크 오류 수정
  src/components/card/voteCard.tsx
  src/components/card/voteEndCard.tsx
  src/components/navigation/navigation.tsx
  src/features/home/components/swipCard.tsx
  src/features/home/components/voteSwiper_framer.tsx
  src/features/home/pages/homePage.tsx
  src/features/home/stores/voteCardStore.ts
Labels: 🐛 BugFix, 🌐 FE

#61 [bugfix] 배포 QA 1차 수정
  src/app/AppLayout.tsx
  src/components/card/voteCard.tsx
  src/components/card/voteCardPreview.tsx
  src/components/card/voteNoMoreCard.tsx
  src/components/item/voteItem.tsx
  src/components/modal/loginRequiredModal.tsx
  src/components/modal/modal.tsx
  src/components/modal/noVoteAvailableModal.tsx
  src/components/navigation/navigation.tsx
  src/features/group/components/createGroupForm.tsx
  src/features/home/components/voteSwiper_framer.tsx
  src/features/home/pages/homePage.tsx
  src/features/login/pages/authCallback.tsx
  src/features/make/components/makeVoteForm.tsx
  src/features/make/components/voteCardPreviewModal.tsx
  src/features/research/pages/researchDetail.Page.tsx
  src/features/user/pages/userPage.tsx
  src/mocks/handlers/userHandlers.ts
Labels: 🐛 BugFix, 🌐 FE

#63 [bugfix] QA 및 디자인 피드백 반영
  src/app/AppLayout.tsx
  src/assets/vote.svg
  src/components/item/voteItem.tsx
  src/components/loading/loadingPage.tsx
  src/components/modal/addGroupModal.tsx
  src/components/modal/inviteCodeCheckModal.tsx
  src/components/modal/loginRequiredModal.tsx
  src/components/navigation/navigation.tsx
  src/features/group/components/createGroupForm.tsx
  src/features/group/lib/groupSchema.ts
  src/features/home/stores/voteCardStore.ts
  src/features/login/pages/authCallback.tsx
  src/features/make/components/makeVoteForm.tsx
  src/features/make/lib/makeVoteSchema.ts
  src/features/research/components/researchList.tsx
  src/features/research/pages/researchDetail.Page.tsx
  src/features/user/components/userCard.tsx
  src/features/user/lib/userSchema.ts
  src/lib/formatTime.ts
Labels: 🐛 BugFix, 🌐 FE, 💎 Style

#64 [Feat] QA 2차 수정
  package.json
  src/api/services/user/group/quries.ts
  src/api/services/vote/model.ts
  src/api/services/vote/quries.ts
  src/api/services/vote/service.ts
  src/app/AppLayout.tsx
  src/app/QueryProvider.tsx
  src/components/dropdown/groupDropDown.tsx
  src/components/item/voteItem.tsx
  src/components/modal/addGroupModal.tsx
  src/components/modal/exitUserModal.tsx
  src/components/modal/loginRequiredModal.tsx
  src/features/home/components/swipCard.tsx
  src/features/home/components/tutorial.tsx
  src/features/home/pages/homePage.tsx
  src/features/login/pages/authCallback.tsx
  src/features/make/components/makeVoteForm.tsx
  src/features/user/components/userCard.tsx
  src/features/user/lib/userSchema.ts
  src/lib/fullReset.ts
  src/lib/messageMap.ts
  src/stores/groupStore.ts
  src/stores/tutorialStore.ts
  src/stores/userStore.ts
  src/styles/globals.css
Labels: 🐛 BugFix, 🌐 FE, 🌏 Deploy

#65 [Feat] QA3
  src/api/services/user/quries.ts
  src/api/services/vote/quries.ts
  src/app/AppLayout.tsx
  src/components/card/groupCard.tsx
  src/components/card/voteCard.tsx
  src/components/card/voteCardPreview.tsx
  src/components/header/header.tsx
  src/components/item/voteItem.tsx
  src/features/group/components/createGroupForm.tsx
  src/features/home/components/tutorial.tsx
  src/features/home/components/voteSwiper_framer.tsx
  src/features/home/pages/homePage.tsx
  src/features/research/components/researchList.tsx
  src/features/user/components/userCard.tsx
  src/stores/userStore.ts
Labels: 🌐 FE, 🌏 Deploy, 💎 Style

#67 [배포] PRD
  src/api/services/user/group/quries.ts
  src/api/services/vote/quries.ts
Labels: 🌐 FE, 🌏 Deploy

#74 [Style] 튜토리얼 스타일 수정
  src/components/card/voteCard.tsx
  src/components/card/voteCardPreview.tsx
  src/features/home/components/tutorial.tsx
Labels: 🌐 FE, 💎 Style

#75 [Bugfix] 드롭다운 초기화 오류 수정
  src/stores/groupStore.ts
Labels: 🐛 BugFix, 🌐 FE

#76 Bugfix/#73 cardlist
  src/components/dropdown/groupDropDown.tsx
  src/features/home/components/voteSwiper_framer.tsx
  src/features/home/stores/voteCardStore.ts
Labels: 🐛 BugFix, 🌐 FE

#81 [BugFix] 투표 중복 생성 오류 해결
  src/features/make/components/voteCardPreviewModal.tsx
Labels: 🐛 BugFix, 🌐 FE

#83 [Feature] 스와이프버튼 추가
  src/features/home/components/swipCard.tsx
  src/features/home/components/voteDirectionButtonGroup.tsx
  src/features/home/components/voteSwiper_framer.tsx
Labels: ✨ Feature, 🌐 FE

#87 [Bugfix] 미리보기 타이머 오류 수정
  src/components/card/voteCardPreview.tsx
  src/lib/formatTime.ts
Labels: 🐛 BugFix, 🌐 FE

#96 [Style] 로고, 버튼 색상 조정
  public/moa_app_logo.svg
  src/assets/pass.svg
Labels: 🌐 FE, 💎 Style

#98 Release v1.1.0
  .github/workflows/cicd-bigbang-prd.yml
  index.html
  public/moa_app_logo.svg
  public/vite.svg
  src/App.tsx
  src/app/AppLayout.tsx
  src/assets/home.png
  src/assets/pass.svg
  src/components/card/voteCardPreview.tsx
  src/components/modal/modal.tsx
  src/features/home/components/tutorial.tsx
  src/features/home/pages/homePage.tsx
  src/stores/tutorialStore.ts
  src/styles/layout.css
Labels: 🌐 FE, 🌏 Deploy

#113 Feature/102 voteresult icon
  src/assets/voteCheckIcon.svg
  src/components/item/voteItem.tsx
  src/features/research/pages/researchDetail.Page.tsx
  src/styles/layout.css
Labels: 🐛 BugFix, ✨ Feature, 🌐 FE

#122 feat: 모바일 스타일 개선
  package.json
  pnpm-lock.yaml
  src/assets/moa_home.svg
  src/components/Icon/icon.tsx
  src/components/header/header.tsx
  src/components/loading/loadingCard.tsx
  src/components/navigation/navigation.tsx
  src/features/home/components/tutorial.tsx
  src/features/home/components/voteDirectionButtonGroup.tsx
  src/features/research/components/researchList.tsx
  src/features/research/pages/researchDetail.Page.tsx
  src/features/research/pages/researchPage.tsx
  src/features/user/components/userFeedbackWidget.tsx
  src/type/svg.d.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: 🌐 FE, 💎 Style

#127 release: v1.2.0(Closes #125)
  .github/ISSUE_TEMPLATE/sprint-issue-templete---bugfix-templete-.md
  .github/ISSUE_TEMPLATE/sprint-issue-templete.md
  .github/workflows/cicd-bigbang-dev.yml
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.cjs
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/services/vote/model.ts
  src/assets/home.png
  src/assets/moa_home.svg
  src/assets/voteCheckIcon.svg
  src/components/Icon/icon.tsx
  src/components/card/groupCard.tsx
  src/components/card/voteCard.tsx
  src/components/dropdown/groupDropDown.tsx
  src/components/header/header.tsx
  src/components/item/voteItem.tsx
  src/components/loading/loadingCard.tsx
  src/components/modal/addGroupModal.tsx
  src/components/modal/exitUserModal.tsx
  src/components/modal/modal.tsx
  src/components/navigation/navigation.tsx
  src/features/group/components/createGroupForm.tsx
  src/features/home/components/swipCard.tsx
  src/features/home/components/tutorial.tsx
  src/features/home/components/voteDirectionButtonGroup.tsx
  src/features/home/components/voteSwiper_framer.tsx
  src/features/home/components/voteSwiper_tinder.tsx
  src/features/home/pages/homePage.tsx
  src/features/home/stores/batchVoteStore.ts
  src/features/login/components/kakaoButton.tsx
  src/features/make/components/makeVoteForm.tsx
  src/features/make/components/voteCardPreviewModal.tsx
  src/features/make/lib/makeVoteSchema.ts
  src/features/research/components/researchList.tsx
  src/features/research/pages/researchDetail.Page.tsx
  src/features/research/pages/researchPage.tsx
  src/features/user/components/userCard.tsx
  src/features/user/components/userFeedbackWidget.tsx
  src/lib/fullReset.ts
  src/lib/trackEvent.ts
  src/mocks/handlers/voteCardHandlers.ts
  src/styles/globals.css
  src/styles/index.css
  src/styles/layout.css
  src/type/svg.d.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: 🌐 FE, 🌏 Deploy

#133 cicd: 환경별 동적 구성으로 워크플로우 통합
  .github/workflows/cicd-bigbang-prd.yml
  .github/workflows/gcp-v2-deployment.yml
Labels: CI/CD
